# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b5047d7dca0b4813d5069300a513cdd36f5f28d3dc8ab84ded85ab604bf3b2d82967482f16cace8e5eaa5bc1ba3cf5f5c2305cf20bcd768ef15e22a438e29ec

test:
  secret_key_base: 598e9d658e00a6d1969345d3b7c4e9a29b3994200410d548384b511f7852ed7977aefbd503f7ce9b919eb6f6cb58df62d23ccc1886ff6ea615f26a8b25f3fac5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
